services:
  postgres:
    container_name: postgres_db_product
    image: postgres:16
    env_file: ./.env
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
